version: '3.8'

services:
  backend:
    build: ./express-app
    ports:
      - "${PORT}:3000"
    env_file:
      - .env

  frontend:
    build:
      context: ./svelte-app
      args:
        VITE_PUBLIC_BACKEND_URL: ${VITE_PUBLIC_BACKEND_URL}
    ports:
      - 4000:80
    env_file:
      - .env
